services:
  - type: web
    name: shopify-ticketing-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && echo "=== Build directory contents ===" && ls -la build/ && echo "=== First 20 lines of build/index.js ===" && head -20 build/index.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: SCOPES
        value: write_products,read_orders,read_customers,write_customers
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: Validiam <noreply@validiam.com>
