# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "validiam"
client_id = ""
application_url = "https://your-tunnel-url.com"
embedded = true

[access_scopes]
scopes = "write_products,read_orders,write_webhooks,read_customers"

[auth]
redirect_urls = [
  "https://your-tunnel-url.com/auth/callback",
  "https://your-tunnel-url.com/auth/shopify/callback",
  "https://your-tunnel-url.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/api/webhooks/orders/create"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
