# Learn more: https://shopify.dev/docs/api/checkout-ui-extensions/configuration

api_version = "2024-10"

[[extensions]]
uid = "5c574df2-4c40-b0f9-0b53-3397018f968e9aa55a24"
type = "ui_extension"
name = "Order Status QR Codes"
handle = "order-status-qr"

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/index.tsx"
